apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "squid-proxy.fullname" . }}
  labels:
    {{- include "squid-proxy.labels" . | nindent 4 }}
data:
  squid.conf: |
{{ .Values.squidConfig | indent 4 }}
